---
- name: Genrate TLS Key Put in Nginx
  hosts: demo1
  sudo: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost

  tasks:

  - name: install Nginx
    apt: name=nginx update_cache=yes 

  - name: create directories for ssl certificate
    file: path=/etc/nginx/ssl state=directory

  - name: copy TLS Key
    copy: src=files/nginx.key dest={{key_file}} owner=root mode=0600
    notify: restart nginx

  - name: copy TLS certificate
    copy: src=files/nginx.crt dest={{cert_file}}
    notify: restart nginx

  - name: copy nginx config file
    template: src=files/nginx.conf.j2 dest={{conf_file}}
    notify: restart nginx

  - name: enable configuration
    file: >
      dest=/etc/nginx/sites-enabled/default
      src=/etc/nginx/sites-available/default
      state=link
    notify: restart nginx

  - name: copy index.html
    template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0664

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
