Vagrant.configure("2") do |config|

 config.ssh.insert_key = false
  
 config.vm.define "vagrant1" do |vagrant1|
   vagrant1.vm.box = "ubuntu/trusty64"
   vagrant1.vm.host_name = "vargant1"
   vagrant1.vm.network "private_network", ip: "192.168.33.12"
 end
 config.vm.define "vagrant2" do |vagrant2|
   vagrant2.vm.box = "ubuntu/trusty64"
   vagrant2.vm.host_name = "vargant2"
   vagrant2.vm.network "private_network", ip: "192.168.33.13"
 end
 config.vm.define "vagrant3" do |vagrant3|
   vagrant3.vm.box = "ubuntu/trusty64"
   vagrant3.vm.host_name = "vargant3"
   vagrant3.vm.network "private_network", ip: "192.168.33.14"
 end
end
